### ISSUE TITLE
Provided pretrained VGG16 weights

### ISSUE THREAD

**Issue by Stark16** [dedhiaparth98/face-recognition#2]
Hey, excellent blog! Really well explained and written. I was trying to train a model myself as a side learning project, I am not able train the VGG16 model that you trained according to the paper link, but the link does not lead anywhere. Would you be kind enough to provide me the pretrianed weights that I can use to do transfer learning?

**Comment by dedhiaparth98** [comment]
Hey @Stark16,
Sorry for delayed response. Here is the link to the pre-trained weights used by me.

[Drive Link](https://drive.google.com/file/d/1LrkgfwX13XMFIBHDLqZRjd4SFdwI4fka/view?usp=share_link)

**Comment by Stark16** [comment]
Thank you for your help!
